services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-database:/data/db
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-database:/data/db
  backend:
    build: ./server/.
    image: courso_backend_image
    container_name: courso_backend
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
  frontend:
    build: ./client/.
    image: course_frontend_image
    container_name: courso_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
volumes:
  mongo-database:
  redis-database:
